import type { Metadata } from "next";
import QrGeneratorShell from "@/components/tools/qr/QrGeneratorShell";
import ToolErrorBoundary from "@/components/tools/ToolErrorBoundary";

export const metadata: Metadata = {
  title: "QR Code Generator",
  description: "Create custom QR codes for URLs, text, and more. Free, fast, and private — all in your browser. Generate and download QR codes instantly.",
};

export default function QrGeneratorPage() {
  return (
    <ToolErrorBoundary>
      <QrGeneratorShell
      title="QR Code Generator"
      description="Generate QR codes from any text or URL. Enter your content below and instantly see your QR code. Download as PNG or copy the encoded text."
      fields={[
        { key: "content", label: "Text or URL", placeholder: "https://example.com", required: true },
      ]}
      formatType="text"
      faqs={[
        {
          question: "What can I put in a QR code?",
          answer: "Any text, URL, phone number, or plain text. QR codes can store up to about 100 characters reliably at the size generated by this tool.",
        },
        {
          question: "How is the QR code generated?",
          answer: "The QR code is generated entirely in your browser using JavaScript and the Canvas API. It implements Reed-Solomon error correction for reliable scanning.",
        },
        {
          question: "Can I download the QR code?",
          answer: "Yes, click the Download PNG button to save your QR code as a high-quality PNG image.",
        },
        {
          question: "Is my data sent to a server?",
          answer: "Never. Everything runs in your browser. Your content never leaves your device.",
        },
      ]}
    />
    </ToolErrorBoundary>
  );
}
